<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TicTacToe.Application\TicTacToe.Services.csproj" />
    <ProjectReference Include="..\TicTacToe.Base\TicTacToe.Repository.csproj" />
    <ProjectReference Include="..\TicTacToe.Core\TicTacToe.Core.csproj" />
  </ItemGroup>

</Project>
